name: Upload release

on:
  push:
    branches:
      - main

jobs:
  npm_build:
    runs-on: ubuntu-latest
    name: Upload release
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Install all dependencies
        working-directory: ./webapp
        run: npm install

      - name: Build
        working-directory: ./webapp
        run: npm run build

      - name: Upload release
        uses: actions/upload-artifact@v2
        with:
          name: release-build
          path: ./webapp/build/

      - name: Create zip file
        working-directory: ./webapp/
        run: zip -r release-build.zip build/*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-build
          files: ./webapp/release-build.zip
